SELECT * FROM ( 
 SELECT DISTINCT 
 	DA7_PERCUR COD_ROTA, DA8_DESC DESC_ROTA,  
     C6_FILIAL FILIAL, TRIM(ACY_DESCRI) CANAL, ZH_DESSEG SEGMENTO, 
     (CASE WHEN C5_EMISSAO <>  ' ' THEN TO_CHAR(TO_DATE(C5_EMISSAO, 'yyyy/MM/dd'), 'dd/MM/yyyy') ELSE C5_EMISSAO END) EMISSAO, 
     (CASE WHEN C6_ENTREG <>  ' ' THEN TO_CHAR(TO_DATE(C6_ENTREG, 'yyyy/MM/dd'), 'dd/MM/yyyy') ELSE C6_ENTREG END) PREVFAT,  
     (CASE WHEN C6_DATFAT <>  ' ' THEN TO_CHAR(TO_DATE(C6_DATFAT, 'yyyy/MM/dd'), 'dd/MM/yyyy') ELSE C6_DATFAT END) DTFATURAMENTO, 
     F2_HORA HORA, (CASE WHEN C6_X_DTENT <>  ' ' THEN TO_CHAR(TO_DATE(C6_X_DTENT, 'yyyy/MM/dd'), 'dd/MM/yyyy') ELSE C6_X_DTENT END) PREVENT, 
     C6_NOTA NOTA, C6_SERIE SERIE, D2_LOTECTL LOTE, 
       (CASE WHEN F2_TPFRETE <> NULL  
          THEN (CASE WHEN F2_TPFRETE = 'C' THEN 'CIF' WHEN F2_TPFRETE = 'F' THEN 'FOB' ELSE F2_TPFRETE END) 
       ELSE 
          (CASE WHEN C5_TPFRETE = 'C' THEN 'CIF' WHEN C5_TPFRETE = 'F' THEN 'FOB' ELSE F2_TPFRETE END)  
       END) FRETE, 
     NVL(D2_TES, C6_TES) TES, 
     F4_TEXTO TESTXT, TRIM(X5_DESCRI) OPERACAO, NUM, ITEM, C6_X_NRORD NORD, C9_CARGA CARGA, C6_CLI CLIENTE, C6_LOJA LOJA, 
     TRIM(A1_NOME) RAZSOC, TRIM(A1_NREDUZ) FANTASIA, A1_END ENDERECO, A1_BAIRRO BAIRRO, 
     A1_MUN MUNICIPIO, A1_EST UF, BX_DESC LINHA, B1_X_CODBE CODANT, SUBSTR(C6_PRODUTO, 1,2) TPROD, C6_PRODUTO PRODUTO, TRIM(C6_DESCRI) DESCRICAO,  C6_UM UM, 
     NVL(D2_QUANT,C6_QTDVEN) QTD, (B1_PESO * NVL(D2_QUANT,C6_QTDVEN)) PESO, NVL(D2_PRCVEN,C6_PRCVEN) PRCUNIT,  NVL(D2_TOTAL,C6_VALOR) PRCTOTAL, NVL(D2_COMIS1,C6_COMIS1) COMISSAO, 
     A1_X_DESCF DESCFIN,  
     	(CASE  
             WHEN C9_BLCRED = '01' THEN 'BLOQUEIO DE CREDITO'  
             WHEN C9_BLCRED = '02' THEN 'BLOQUEIO POR ESTOQUE'  
             WHEN C9_BLCRED = '04' THEN 'VENC LIMITE DE CREDITO'  
             WHEN C9_BLCRED = '05' THEN 'BLOQUEIO MANUAL'  
             WHEN C9_BLCRED = '06' THEN 'BLOQUEIO POR RISCO'  
             WHEN C9_BLCRED = '09' THEN 'LIBERACAO DE CREDITO REJEITADA'  
             WHEN C9_BLCRED = '10' THEN 'FATURADO' 
             WHEN C9_BLCRED = ' '  THEN ' ' 
         ELSE NVL(C9_BLCRED,'BLOQUEIO POR COND PAGTO') END) BLQCRED,  
      TRIM(E4_DESCRI) CONDPAG,  
     TRIM(C5_MENNOTA) MENPED, TRIM(F2_MENNOTA) MENNOTA, TRIM(A1_X_OBSNF) MENCLI, TRIM(A1_X_OBSIN) OBSINT, 
     TRIM(A1_OBSERV) OBSERV, (CASE WHEN ZH_X_CORIN = ' ' THEN A3_SUPER ELSE ZH_X_CORIN END) CODSUPER, 
     (CASE  
             WHEN A3_SUPER <> ' '  
             THEN  
                 (SELECT DISTINCT TRIM(A3_NOME) A3_NOME FROM SA3010 WHERE A3_COD = (CASE WHEN ZH_X_CORIN = ' ' THEN SA3.A3_SUPER ELSE ZH_X_CORIN END) AND D_E_L_E_T_ <> '*') 
             ELSE  
                 ' ' 
         END) NOMESUPER, 
      C5_VEND1 CODVEN, TRIM(A3_NOME) NOMEVEND, TRIM(A4_NOME) TRANSP, DAK_CAMINH PLACA, 
     '' NFORI, '' SRORI, '' MOTDEV, '' LOTDEV 
 FROM SC6010 SC6 
  
 RIGHT JOIN ( 
    SELECT  
        DISTINCT C6_FILIAL FILIAL, C6_NUM NUM, C6_ITEM ITEM, SUBSTR(C6_PRODUTO, 1,2) TPROD 
    FROM SC6010  
    WHERE C6_DATFAT BETWEEN '20230331' AND '20230331' 
    AND C6_NOTA <> ' ' 
    AND (C6_BLQ <> 'R' OR C6_QTDENT > 0) 
    AND C6_FILIAL BETWEEN '020105' AND '020105' 
    AND SUBSTR(C6_PRODUTO, 1,2) IN ('PA') 
    AND d_e_l_e_t_ <> '*' 
    ORDER BY C6_FILIAL, C6_NUM 
 ) BS 
 ON SC6.C6_FILIAL = BS.FILIAL 
 AND SC6.C6_NUM = BS.NUM 
 AND SC6.C6_ITEM = BS.ITEM 
 AND SC6.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SC5010 SC5 
 ON SC5.C5_FILIAL = BS.FILIAL 
 AND SC5.C5_NUM = BS.NUM 
 AND SUBSTR(C6_PRODUTO, 1,2) = BS.TPROD 
 AND SC5.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SA1010 SA1 
 ON SA1.A1_COD = SC6.C6_CLI 
 AND SA1.A1_LOJA = SC6.C6_LOJA 
 AND SA1.D_E_L_E_T_ <> '*' 
  
    LEFT JOIN DA7010 DA7 
    ON DA7.DA7_CLIENT = SC6.C6_CLI  
    AND DA7.DA7_LOJA = SC6.C6_LOJA  
    AND DA7.D_E_L_E_T_ <> '*'  
   
  LEFT JOIN DA8010 DA8 
  ON DA8.DA8_COD = DA7.DA7_PERCUR 
  AND DA8.D_E_L_E_T_ <> '*'  
  
 LEFT JOIN SF2010 SF2 
 ON SF2.F2_FILIAL = BS.FILIAL 
 AND SF2.F2_DOC = C6_NOTA 
 AND SF2.F2_SERIE = C6_SERIE 
 AND SF2.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SC9010 SC9  
 ON SC9.C9_FILIAL = BS.FILIAL  
 AND SC9.C9_PEDIDO = BS.NUM  
 AND SC9.C9_ITEM = BS.ITEM  
 AND SC9.D_E_L_E_T_ <> '*'  
  
 LEFT JOIN SD2010 SD2  
 ON SD2.D2_FILIAL = BS.FILIAL  
 AND SD2.D2_DOC = C9_NFISCAL  
 AND SD2.D2_SERIE = C9_SERIENF  
 AND SD2.D2_ITEMPV = C9_ITEM 
 AND SD2.D2_LOTECTL = C9_LOTECTL 
 AND SD2.D_E_L_E_T_ <> '*'  
  
 LEFT JOIN SB1010 SB1 
 ON SB1.B1_COD = SC6.C6_PRODUTO 
 AND SB1.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SA3010 SA3 
 ON SA3.A3_COD = C5_VEND1 
 AND SA3.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SE4010 SE4 
 ON SE4.E4_CODIGO = C5_CONDPAG 
 AND SE4.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SF4010 SF4 
 ON SF4.F4_CODIGO = NVL(D2_TES, C6_TES) 
 AND SF4.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SBX010 SBX 
 ON TRIM(BX_CONJUN) = 'UN' 
 AND TRIM(BX_CODOP) = SUBSTR(C6_PRODUTO, 12,2) 
 AND SBX.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN ACY010 ACY 
 ON ACY.ACY_FILIAL = BS.FILIAL 
 AND ACY.ACY_GRPVEN = C5_X_CLIGR 
 AND ACY.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SX5010 SX5 
 ON X5_TABELA = 'DJ' 
 AND X5_FILIAL = BS.FILIAL 
 AND X5_CHAVE = C6_OPER 
 AND SX5.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SZH010 SZH 
 ON SZH.ZH_GRPCLI = A1_GRPVEN 
 AND SZH.ZH_SEG = A1_X_SEG 
 AND SZH.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN DAK010 DAK  
 ON DAK.DAK_COD = C9_CARGA  
 AND DAK.DAK_FILIAL = BS.FILIAL   
 AND DAK.D_E_L_E_T_ <> '*'   
  
 LEFT JOIN SA4010 SA4 
 ON A4_COD = DAK_TRANSP 
 AND SA4.D_E_L_E_T_ <> '*' 
  
 UNION ALL ( 
 SELECT DISTINCT 
 	'' COD_ROTA, '' DESC_ROTA, 
     FT_FILIAL FILIAL, TRIM(ACY_DESCRI) CANAL, ZH_DESSEG SEGMENTO, TO_CHAR(TO_DATE(FT_EMISSAO, 'yyyy/MM/dd'), 'dd/MM/yyyy') EMISSAO,  
     '' PREVFAT, TO_CHAR(TO_DATE(FT_ENTRADA, 'yyyy/MM/dd'), 'dd/MM/yyyy') DTFATURAMENTO,  
     F1_HORA HORA, '' PREVENT, FT_NFISCAL NOTA, FT_SERIE SERIE, '' LOTE, '' FRETE, FT_TES TES, F4_TEXTO TESTXT,  
     '' OPERACAO, D2_PEDIDO NUM, '' ITEM, '' NORD, '' CARGA, FT_CLIEFOR CLIENTE, FT_LOJA LOJA, TRIM(A1_NOME) RAZSOC,  
     TRIM(A1_NREDUZ) FANTASIA, A1_END ENDERECO, A1_BAIRRO BAIRRO, A1_MUN MUNICIPIO, A1_EST UF, '' LINHA,  
     B1_X_CODBE CODANT, SUBSTR(FT_PRODUTO, 1,2) TPROD, FT_PRODUTO PRODUTO, TRIM(B1_DESC) DESCRICAO, B1_UM UM, (FT_QUANT*-1) QTD, (B1_PESO*(FT_QUANT*-1)) PESO, (FT_PRCUNIT*-1) PRCUNIT,  
     (FT_TOTAL*-1) PRCTOTAL, D2_COMIS1 COMISSAO, A1_X_DESCF DESCFIN, '' BLQCRED, '' CONDPAG, TRIM(F1_MENNOTA) MENPED,  
     FT_OBSERV MENNOTA, TRIM(A1_X_OBSNF) MENCLI, TRIM(A1_X_OBSIN) OBSINT, TRIM(A1_OBSERV) OBSERV,  
     (CASE WHEN ZH_X_CORIN = ' ' THEN A3_SUPER ELSE ZH_X_CORIN END) CODSUPER,  
     (CASE  
             WHEN A3_SUPER <> ' '  
             THEN  
                 (SELECT DISTINCT TRIM(A3_NOME) A3_NOME FROM SA3010 WHERE A3_COD = (CASE WHEN ZH_X_CORIN = ' ' THEN SA3.A3_SUPER ELSE ZH_X_CORIN END) AND D_E_L_E_T_ <> '*') 
             ELSE  
                 ' ' 
         END) NOMESUPER,  D1_X_VEORI CODVEN, 
     TRIM(A3_NOME) NOMEVEND, '' TRANSP, '' PLACA, FT_NFORI NFORI, FT_SERORI SRORI, TRIM(M4_FORMULA) MOTDEV, D1_LOTECTL LOTDEV 
 FROM SFT010 SFT 
 RIGHT JOIN ( 
     SELECT DISTINCT 
         FT_FILIAL FILIAL, FT_ENTRADA ENTRADA, FT_EMISSAO EMISSAO,  
         FT_NFISCAL NOTA, FT_SERIE SERIE, FT_NFORI ONFORI, FT_SERORI SORI, 
         FT_TIPO TIPO, FT_CLIEFOR CLIENTE, FT_LOJA LOJA, FT_PRODUTO PRODUTO 
     FROM SFT010 
     WHERE FT_TIPO = 'D' 
     AND FT_FILIAL BETWEEN '020105' AND '020105' 
     AND FT_ENTRADA BETWEEN '20230331' AND '20230331' 
     AND FT_OBSERV NOT LIKE '%CANCE%' 
     AND SUBSTR(FT_PRODUTO, 1,2) IN ('PA') 
     AND D_E_L_E_T_ <> '*' 
 ) BSD 
 ON FT_FILIAL = BSD.FILIAL 
 AND FT_ENTRADA = BSD.ENTRADA 
 AND FT_NFISCAL = BSD.NOTA 
 AND FT_SERIE = BSD.SERIE 
 AND FT_TIPO = BSD.TIPO 
 AND FT_PRODUTO = BSD.PRODUTO 
 AND SFT.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SF1010 SF1 
 ON F1_DOC = BSD.NOTA 
 AND F1_SERIE = BSD.SERIE 
 AND F1_TIPO = 'D' 
 AND F1_FORNECE = BSD.CLIENTE 
 AND F1_LOJA = BSD.LOJA 
 AND SF1.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SM4010 SM4 
 ON M4_CODIGO = F1_MENPAD 
 AND SM4.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SD1010 SD1 
 ON D1_DOC = BSD.NOTA 
 AND D1_SERIE = BSD.SERIE 
 AND D1_TIPO = 'D' 
 AND D1_FORNECE = BSD.CLIENTE 
 AND D1_LOJA = BSD.LOJA 
 AND D1_ITEM = FT_ITEM 
 AND SD1.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SD2010 SD2 
 ON D2_FILIAL = BSD.FILIAL 
 AND D2_DOC = FT_NFORI 
 AND D2_SERIE = FT_SERORI 
 AND SD2.D_E_L_E_T_ <> '*' 
 AND D2_ITEM = FT_ITEMORI 
  
 LEFT JOIN SF4010 SF4 
 ON F4_CODIGO = FT_TES 
 AND SF4.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SA1010 SA1 
 ON A1_COD = BSD.CLIENTE 
 AND A1_LOJA = BSD.LOJA 
 AND SA1.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN ACY010 ACY 
 ON ACY.ACY_FILIAL = BSD.FILIAL 
 AND ACY.ACY_GRPVEN = FT_IDENTF3 
 AND ACY.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SB1010 SB1 
 ON B1_COD = FT_PRODUTO 
 AND SB1.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SA3010 SA3 
 ON A3_COD = D1_X_VEORI 
 AND SA3.D_E_L_E_T_ <> '*' 
  
 LEFT JOIN SZH010 SZH 
 ON SZH.ZH_GRPCLI = A1_GRPVEN 
 AND SZH.ZH_SEG = A1_X_SEG 
 AND SZH.D_E_L_E_T_ <> '*' 
)

UNION ALL (
SELECT 
    '' COD_ROTA, '' DESC_ROTA, ZS_FILIAL FILIAL, A1_GRPVEN CANAL, ZH_DESSEG SEGMENTO, ZQ_DATA EMISSAO, ZS_DTFIM PREVFAT, '' DTFATURAMENTO, 
    '' HORA, '' PREVENT, '' NOTA, '' SERIE, '' LOTE, '' FRETE, '' TES, '' TESTXT, 
    'NEGOCIACAO DE VENDA' OPERACAO, ZS_COD NUM, ZS_ITEM ITEM, ZS_SEQ NORD, '' CARGA, ZQ_CLIENTE CLIENTE, ZQ_LOJA LOJA, ZQ_NOME RAZSOC, 
    A1_NREDUZ FANTASIA, A1_END ENDERECO, A1_BAIRRO BAIRRO, A1_MUN MUNICIPIO, A1_EST UF, BX_DESC LINHA, B1_X_CODBE CODANT, 
    SUBSTR(ZS_PRODUTO, 1,2) TPROD, ZS_PRODUTO PRODUTO, ZS_DESC DESCRICAO, ZS_UM UM, (ZS_QTDPRG-ZS_QTDENT) QTD, ((ZS_QTDPRG-ZS_QTDENT)*B1_PESO) PESO, 
    ZS_PRCVEN PRCUNIT, (ZS_PRCVEN * (ZS_QTDPRG-ZS_QTDENT)) PRCTOTAL, 
    (SELECT DISTINCT ZR_COMIS1 FROM SZR010 WHERE ZR_FILIAL = ZS_FILIAL AND ZR_COD = ZS_COD AND ZR_ITEM = ZS_ITEM) COMISSAO, 
    A1_X_DESCF DESCFIN, '' BLQCRED, ZQ_CONDPG CONDPAG, ZS_OBSPRG MENPED, '' MENNOTA, 
    TRIM(A1_X_OBSNF) MENCLI, ZQ_PEDPKT OBSINT, TRIM(A1_OBSERV) OBSERV, (CASE WHEN ZH_X_CORIN = ' ' THEN A3_SUPER ELSE ZH_X_CORIN END) CODSUPER, 
    (CASE  
        WHEN A3_SUPER <> ' '  
        THEN  
            (SELECT DISTINCT TRIM(A3_NOME) A3_NOME FROM SA3010 WHERE A3_COD = (CASE WHEN ZH_X_CORIN = ' ' THEN SA3.A3_SUPER ELSE ZH_X_CORIN END) AND D_E_L_E_T_ <> '*') 
        ELSE  
            ' ' 
    END) NOMESUPER, 
    ZQ_VEND1 CODVEN, 
    TRIM(A3_NOME) NOMEVEND, '' TRANSP, '' PLACA, '' NFORI, '' SRORI, '' MOTDEV, '' LOTDEV
    
FROM SZS010 SZS

LEFT JOIN SB1010 SB1
ON SB1.D_E_L_E_T_ <> '*'
AND B1_COD = ZS_PRODUTO

LEFT JOIN SZQ010 SZQ
ON SZQ.D_E_L_E_T_ <> '*' 
AND ZQ_COD = ZS_COD
AND ZQ_FILIAL = ZS_FILIAL

LEFT JOIN SA3010 SA3
ON SA3.A3_COD = ZQ_VEND1
AND SA3.D_E_L_E_T_ <> '*'

LEFT JOIN SA1010 SA1
ON SA1.D_E_L_E_T_ <> '*' 
AND A1_COD = ZQ_CLIENTE
AND A1_LOJA = ZQ_LOJA

LEFT JOIN SZH010 SZH 
ON SZH.ZH_GRPCLI = A1_GRPVEN 
AND SZH.ZH_SEG = A1_X_SEG 
AND SZH.D_E_L_E_T_ <> '*' 

LEFT JOIN SBX010 SBX
ON SBX.D_E_L_E_T_ <> '*'
AND TRIM(BX_CONJUN) = 'UN'
AND TRIM(BX_CODOP) = SUBSTR(ZS_PRODUTO, 12,2)

WHERE SZS.D_E_L_E_T_ <> '*' 
AND ZS_FILIAL BETWEEN '020105' AND '020105'
AND ZS_DTFIM BETWEEN '20230301' AND '20230331'
)
)  
 ORDER BY FILIAL, NUM, ITEM 
 
 ;